export enum ConfigKeyEnum {
  USER_HASH_SECRET = 'USER_HASH_SECRET',
  USER_JWT_SECRET = 'USER_JWT_SECRET',
  USER_JWT_EXPIRES_IN = 'USER_JWT_EXPIRES_IN',
  ORM_TYPE = 'ORM_TYPE',
  ORM_HOST = 'ORM_HOST',
  ORM_PORT = 'ORM_PORT',
  ORM_USERNAME = 'ORM_USERNAME',
  ORM_PASSWORD = 'ORM_PASSWORD',
  ORM_DATABASE = 'ORM_DATABASE',
}
