version: "3.9"
services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    links:
      - postgres
    env_file:
      - .env.production
  postgres:
    image: postgres
    container_name: database
    environment:
      POSTGRES_DB: "index"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"